[build]
  publish = "public"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
